import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import AuthProvider from "@/providers/AuthProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toast";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar/app-sidebar";

import Script from "next/script";

import { MyStoreProvider } from "@/providers/MyStoreProvider";
import TempEditTaskDialog from "@/app/inbox/temp-edit-task-dialog";
import AddTaskForm from "@/components/(home)/add-task-form";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// NOTE: AuthProvider should be within QueryProvider,
// because fetching the current user is also a query.
// NOTE: should it be?
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <QueryProvider>
          <AuthProvider>
            <MyStoreProvider>
              <TooltipProvider>
                <SidebarProvider
                  defaultOpen={false}
                  style={
                    {
                      "--sidebar-width": "350px",
                    } as React.CSSProperties
                  }
                >
                  <AppSidebar />
                  {children}
                  <Toaster />
                  <TempEditTaskDialog />
                  <AddTaskForm />

                </SidebarProvider>
              </TooltipProvider>
            </MyStoreProvider>
          </AuthProvider>
        </QueryProvider>
        <Script
          src="https://unpkg.com/react-scan/dist/auto.global.js"
          crossOrigin="anonymous"
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
